-- EXCOMERCAFE - Personas responsables por agromercado
-- Ejecutar en Supabase SQL Editor.

create table if not exists public.personas_sistema (
  id bigint generated by default as identity primary key,
  local_id text,
  nombre text,
  cargo text,
  telefono text,
  agromercado text,
  payload jsonb,
  creado_en timestamptz default now(),
  actualizado_en timestamptz default now()
);

alter table public.personas_sistema
add column if not exists local_id text,
add column if not exists nombre text,
add column if not exists cargo text,
add column if not exists telefono text,
add column if not exists agromercado text,
add column if not exists payload jsonb,
add column if not exists actualizado_en timestamptz default now();

create unique index if not exists personas_sistema_local_id_key
on public.personas_sistema(local_id);

alter table public.personas_sistema enable row level security;

drop policy if exists "personas_sistema_select" on public.personas_sistema;
drop policy if exists "personas_sistema_insert" on public.personas_sistema;
drop policy if exists "personas_sistema_update" on public.personas_sistema;
drop policy if exists "personas_sistema_delete" on public.personas_sistema;
drop policy if exists "personas_sistema_auth_select" on public.personas_sistema;
drop policy if exists "personas_sistema_auth_insert" on public.personas_sistema;
drop policy if exists "personas_sistema_auth_update" on public.personas_sistema;
drop policy if exists "personas_sistema_auth_delete" on public.personas_sistema;

create policy "personas_sistema_select"
on public.personas_sistema for select
to anon, authenticated
using (true);

create policy "personas_sistema_insert"
on public.personas_sistema for insert
to authenticated
with check (true);

create policy "personas_sistema_update"
on public.personas_sistema for update
to authenticated
using (true)
with check (true);

create policy "personas_sistema_delete"
on public.personas_sistema for delete
to authenticated
using (true);
