-- Portal de vendedores: tabla de envios pendientes.
-- Ejecutar en Supabase SQL Editor.

create table if not exists public.ventas_agromercado_pendientes (
  id bigint generated by default as identity primary key,
  local_id text unique,
  fecha text,
  agromercado text,
  encargado text,
  estado text default 'pendiente',
  ventas numeric default 0,
  gastos numeric default 0,
  remesa numeric default 0,
  payload jsonb,
  revisado_por text,
  revisado_en timestamptz,
  observacion_revision text,
  creado_en timestamptz default now()
);

alter table public.ventas_agromercado_pendientes enable row level security;

drop policy if exists "ventas_pendientes_anon_insert" on public.ventas_agromercado_pendientes;
drop policy if exists "ventas_pendientes_auth_select" on public.ventas_agromercado_pendientes;
drop policy if exists "ventas_pendientes_auth_update" on public.ventas_agromercado_pendientes;
drop policy if exists "ventas_pendientes_auth_delete" on public.ventas_agromercado_pendientes;

create policy "ventas_pendientes_anon_insert"
on public.ventas_agromercado_pendientes for insert
to anon
with check (estado = 'pendiente');

create policy "ventas_pendientes_auth_select"
on public.ventas_agromercado_pendientes for select
to authenticated
using (true);

create policy "ventas_pendientes_auth_update"
on public.ventas_agromercado_pendientes for update
to authenticated
using (true)
with check (true);

create policy "ventas_pendientes_auth_delete"
on public.ventas_agromercado_pendientes for delete
to authenticated
using (true);
